name: "Build and Push Docker-Images"

on:
  push:

jobs:
  #  Frontend:
  #    name: Push Frontend Image
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v4

  Backend:
    name: Push Backend Image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ccm-mgmt/backend

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/backend/Dockerfile
          push: true
          tags: ccm-mgmt/backend:${{ github.ref_name }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}